/* Generated By:JavaCC: Do not edit this line. MapJsonParserConstants.java */
package com.kooobao.common.json.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MapJsonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"{\"",
    "\"}\"",
    "\"{}\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"[]\"",
    "<STRING>",
  };

}
