package com.kooobao.fr.domain.entity;

public enum RecordStatus {

	PAYMENT_SUBMIT, PAYMENT_APPROVED, PAYMENT_PAID, PAYMENT_REJECT, PAYMENT_FAILED, PAYMENT_CANCEL, PAYMENT_BALANCED,

	RECEIVE_SUBMIT, RECEIVE_CONFIRMED, RECEIVE_CANCEL
}
