package com.kooobao.ecom.crm;

public enum ErrorCode {
	// Common
	COMMON_NO_OPERATOR,
	// Customer
	CUST_UPDATE_CHANGE_ID_FORBID, CUST_UPDATE_NOT_OWN, CUST_FOLLOWUP_NO_CUST, CUST_FOLLOWUP_NO_METHOD, CUST_FOLLOWUP_NO_REF,
	// Hint
	HINT_UPDATE_NOT_OWN, HINT_UPDATE_FORBID, HINT_DUPLICATE, HINT_UPDATE_ALREADY_CUSTOMER,
}
